export const ADD_HABBIT = 'ADD_HABBIT'
export const ADD_EXPIRENCE = 'ADD_EXPIRENCE'
export  const MINUS_HEALTH = 'MINUS_HEALTH'
export  const CHANGE_HABBIT = 'CHANGE_HABBIT'
export  const DELETE_HABBIT = 'DELETE_HABBIT'
export  const ADD_TODO_EVERY_DAY = 'ADD_TODO_EVERY_DAY'

